Repository starteryouInc/Starteryou-Website, pull requests merged in 2024-12, with the labels that each got.

#22 Job2 Page Developed and Text API Bugs Fixed
  Starteryou/backend/docs/global.html
  Starteryou/backend/docs/index.html
  Starteryou/backend/docs/models_TextContent.js.html
  Starteryou/backend/docs/routes_textRoutes.js.html
  Starteryou/backend/models/TextContent.js
  Starteryou/backend/routes/index.js
  Starteryou/backend/routes/textRoutes.js
  Starteryou/backend/server.js
  Starteryou/frontend/public/Insta.svg
  Starteryou/frontend/public/Twitter.svg
  Starteryou/frontend/public/fb.svg
  Starteryou/frontend/src/App.jsx
  Starteryou/frontend/src/components/About/BetterFuture.jsx
  Starteryou/frontend/src/components/About/HeroAbout.jsx
  Starteryou/frontend/src/components/About/OurMission.jsx
  Starteryou/frontend/src/components/About/OurVision.jsx
  Starteryou/frontend/src/components/About/Team.jsx
  Starteryou/frontend/src/components/About/TechTeam.jsx
  Starteryou/frontend/src/components/Common/Footer.jsx
  Starteryou/frontend/src/components/Job/AfterSignup/CarrerOptions.jsx
  Starteryou/frontend/src/components/Job/AfterSignup/ExcitingCareer.jsx
  Starteryou/frontend/src/components/Job/AfterSignup/ExploreJob.jsx
  Starteryou/frontend/src/components/Job/AfterSignup/JobHero.jsx
  Starteryou/frontend/src/components/Job/AfterSignup/Reviews.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/DiscoverPath.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/HeroJobPortal.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/JobListing.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/LatestInsight.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/LaunchBanner.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/PathStart.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/UnlockPotential.jsx
  Starteryou/frontend/src/components/JobPage/AppSupport.jsx
  Starteryou/frontend/src/components/JobPage/DiscoverFuture.jsx
  Starteryou/frontend/src/components/JobPage/IdealJob.jsx
  Starteryou/frontend/src/components/JobPage/JobHero.jsx
  Starteryou/frontend/src/components/JobPage/Reviews.jsx
  Starteryou/frontend/src/components/JobPage/TailoredJob.jsx
  Starteryou/frontend/src/components/JobPortal/DiscoverPath.jsx
  Starteryou/frontend/src/components/JobPortal/HeroJobPortal.jsx
  Starteryou/frontend/src/components/JobPortal/JobListing.jsx
  Starteryou/frontend/src/components/JobPortal/UnlockPotential.jsx
  Starteryou/frontend/src/components/Landing/BestBuddy.jsx
  Starteryou/frontend/src/config/api.js
  Starteryou/frontend/src/pages/JobPage.jsx
  Starteryou/frontend/src/pages/JobPageAfter.jsx
  Starteryou/frontend/src/pages/JobPageBefore.jsx
  Starteryou/frontend/src/pages/JobPortalPage.jsx
Labels: enhancement

#26 Create InProgress Page which includes Conditional Rendering using Boolean variable.
  .github/workflows/main.yml
  Starteryou/.vite/deps/_metadata.json
  Starteryou/.vite/deps/package.json
  Starteryou/frontend/package-lock.json
  Starteryou/frontend/package.json
  Starteryou/frontend/src/App.jsx
  Starteryou/frontend/src/components/Common/InProgressPage.jsx
  Starteryou/frontend/src/pages/AboutPage.jsx
  Starteryou/frontend/src/pages/EducationPage.jsx
  Starteryou/frontend/src/pages/HomePage.jsx
  Starteryou/frontend/src/pages/JobPortalPage.jsx
  package-lock.json
Labels: enhancement

#25 Developing Job Feed page using the Figma design
  Starteryou/frontend/public/JobFeedPage/CompanyLogo.svg
  Starteryou/frontend/public/JobFeedPage/Experience.svg
  Starteryou/frontend/public/JobFeedPage/Location.svg
  Starteryou/frontend/public/JobFeedPage/Missing.svg
  Starteryou/frontend/public/JobFeedPage/Pen.svg
  Starteryou/frontend/public/JobFeedPage/SaveJob.svg
  Starteryou/frontend/src/App.jsx
  Starteryou/frontend/src/components/Common/NewsLetter.jsx
  Starteryou/frontend/src/components/JobFeedPage/FilterButtons.jsx
  Starteryou/frontend/src/components/JobFeedPage/JobCard.jsx
  Starteryou/frontend/src/components/JobFeedPage/JobDetailCard.jsx
  Starteryou/frontend/src/components/JobFeedPage/styles/JobFeedComp.css
  Starteryou/frontend/src/pages/JobFeedPage.jsx
  Starteryou/frontend/src/pages/styles/JobFeedPage.css
Labels: enhancement

#44 Fix File Upload API Bugs and Implement on Home Page
  Starteryou/backend/routes/fileRoutes.js
  Starteryou/backend/routes/textRoutes.js
  Starteryou/backend/server.js
  Starteryou/frontend/src/components/About/Team.jsx
  Starteryou/frontend/src/components/Common/NewsLetter.jsx
  Starteryou/frontend/src/components/Landing/BestBuddy.jsx
  Starteryou/frontend/src/components/Landing/BestJob.jsx
  Starteryou/frontend/src/components/Landing/BestJob2.jsx
  Starteryou/frontend/src/components/Landing/BestJob3.jsx
  Starteryou/frontend/src/components/Landing/BestJob4.jsx
  Starteryou/frontend/src/components/Landing/Hero.jsx
  Starteryou/frontend/src/components/Landing/UpcomingFeatures.jsx
Labels: bug, documentation, good first issue

#39 Developed User Profile using the figma design
  Starteryou/backend/package-lock.json
  Starteryou/backend/package.json
  Starteryou/backend/server.js
  Starteryou/backend/utils/logger.js
  Starteryou/docker-compose.yml
  Starteryou/frontend/public/UserProfile/EditPen.svg
  Starteryou/frontend/public/UserProfile/EduHat.svg
  Starteryou/frontend/public/UserProfile/Flag.svg
  Starteryou/frontend/public/UserProfile/GreenTick.svg
  Starteryou/frontend/public/UserProfile/ProjectIcon.svg
  Starteryou/frontend/public/UserProfile/WhiteEditPen.svg
  Starteryou/frontend/src/App.jsx
  Starteryou/frontend/src/components/UserProfile/LeftSide.jsx
  Starteryou/frontend/src/components/UserProfile/LeftSideComponent/SocialPresenceForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSide.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/CoursCertiCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/CoursCertiForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/EducationCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/EducationDetailForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/LanguageForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/LanguagesCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/ProjectCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/ProjectForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/SkillsCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/SkillsInputForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/WorkCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/WorkExperienceForm.jsx
  Starteryou/frontend/src/components/UserProfile/styles/LeftSide.css
  Starteryou/frontend/src/components/UserProfile/styles/RightSide.css
  Starteryou/frontend/src/pages/UserProfile.jsx
Labels: good first issue

#80 Fix Text Formatting Bugs and Implement Image Upload for Team Members
  .vscode/settings.json
  Starteryou/backend/docs/TextContent.js.html
  Starteryou/backend/docs/global.html
  Starteryou/backend/docs/index.html
  Starteryou/backend/routes/fileRoutes.js
  Starteryou/backend/routes/index.js
  Starteryou/backend/routes/textRoutes.js
  Starteryou/frontend/docs/frontend/BetterFuture.jsx.html
  Starteryou/frontend/docs/frontend/HeroAbout.jsx.html
  Starteryou/frontend/docs/frontend/OurMission.jsx.html
  Starteryou/frontend/docs/frontend/OurVision.jsx.html
  Starteryou/frontend/docs/frontend/Team.jsx.html
  Starteryou/frontend/docs/frontend/TechTeam.jsx.html
  Starteryou/frontend/docs/frontend/global.html
  Starteryou/frontend/docs/frontend/index.html
  Starteryou/frontend/docs/frontend/module-OurVision.html
  Starteryou/frontend/jsdoc.conf.json
  Starteryou/frontend/public/devicon_linkedin.svg
  Starteryou/frontend/src/components/About/BetterFuture.jsx
  Starteryou/frontend/src/components/About/OurMission.jsx
  Starteryou/frontend/src/components/About/OurVision.jsx
  Starteryou/frontend/src/components/About/Team.jsx
  Starteryou/frontend/src/components/Common/Footer.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/UnlockPotential.jsx
  Starteryou/frontend/src/pages/AboutPage.jsx
Labels: documentation
