Repository starteryouInc/Starteryou-Website, pull requests merged in 2025-03, with the labels that each got.

#204 Cookie Implementation using Sessions to the users-login.
  Starteryou/backend/db.js
  Starteryou/backend/middleware/sessionTimeout.js
  Starteryou/backend/package.json
  Starteryou/backend/routes/authRoutes.js
  Starteryou/backend/routes/sessionRoutes.js
  Starteryou/backend/routes/userAuthRoutes.js
  Starteryou/backend/server.js
  Starteryou/frontend/src/App.jsx
  Starteryou/frontend/src/components/Auth/UserLogin.jsx
  Starteryou/frontend/src/components/Common/SessionExpired.jsx
  Starteryou/frontend/src/components/Common/SessionTimer.jsx
  Starteryou/frontend/src/config/api.js
Labels: Cookie Mechanism

#205 Update Toast Library for Better UX, Add Badge to Jobs, and Improve Validation
  Starteryou/backend/models/Job.js
  Starteryou/backend/routes/jobRoutes.js
  Starteryou/frontend/package-lock.json
  Starteryou/frontend/package.json
  Starteryou/frontend/src/App.jsx
  Starteryou/frontend/src/components/About/OurMission.jsx
  Starteryou/frontend/src/components/Auth/AdminSignup.jsx
  Starteryou/frontend/src/components/Auth/EmployerSignUp.jsx
  Starteryou/frontend/src/components/Auth/LoginPage.jsx
  Starteryou/frontend/src/components/Auth/Signup.jsx
  Starteryou/frontend/src/components/Auth/UserLogin.jsx
  Starteryou/frontend/src/components/Common/NewsLetter.jsx
  Starteryou/frontend/src/components/Common/wordValidation.js
  Starteryou/frontend/src/components/CompanyDashboard/JobDetailedCard2.jsx
  Starteryou/frontend/src/components/CompanyDashboard/Pages/PostedJobs.jsx
  Starteryou/frontend/src/components/CompanyDashboard/Pages/ProfilePage.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/DiscoverPath.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/HeroJobPortal.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/JobListing.jsx
  Starteryou/frontend/src/components/Job/BeforeSignup/UnlockPotential.jsx
  Starteryou/frontend/src/components/JobFeedPage/ApplyJobCard.jsx
  Starteryou/frontend/src/components/JobFeedPage/CreateJobCard.jsx
  Starteryou/frontend/src/components/JobFeedPage/EditJobCard.jsx
  Starteryou/frontend/src/components/JobFeedPage/JobDetailCard.jsx
  Starteryou/frontend/src/components/Landing/BestBuddy.jsx
  Starteryou/frontend/src/components/Landing/BestJob.jsx
  Starteryou/frontend/src/components/Landing/BestJob2.jsx
  Starteryou/frontend/src/components/Landing/Hero.jsx
  Starteryou/frontend/src/components/UserProfile/LeftSide.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/CoursCertiCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/CoursCertiForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/EditableForms/EditCourse.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/EditableForms/EditEducation.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/EditableForms/EditProject.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/EditableForms/EditWork.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/EducationCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/EducationDetailForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/LanguageForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/ProjectCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/ProjectForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/SkillsInputForm.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/WorkCard.jsx
  Starteryou/frontend/src/components/UserProfile/RightSideComponents/WorkExperienceForm.jsx
  Starteryou/frontend/src/config/api.js
  Starteryou/frontend/src/pages/AboutPage.jsx
  Starteryou/frontend/src/pages/CompanyDashboard.jsx
  Starteryou/frontend/src/pages/JobFeedPage.jsx
  Starteryou/frontend/src/pages/ProfileCarousel.jsx
  Starteryou/frontend/src/pages/UserProfile.jsx
  Starteryou/frontend/src/pages/_app.js
Labels: enhancement

#226 Update main.yml
  .github/workflows/main.yml
Labels: good first issue

#229 Update develop.yml
  .github/workflows/develop.yml
Labels: good first issue

#233 Unit test cases for the Job Portal API's
  Starteryou/backend/__test__/BookmarkedRoutes.test.js
  Starteryou/backend/__test__/CompanyProfileRoutes.test.js
  Starteryou/backend/__test__/JobApplicationRoutes.test.js
  Starteryou/backend/__test__/JobRoutes.test.js
  Starteryou/backend/__test__/ProfileRoutes.test.js
  Starteryou/backend/handlers/BookmarkHandlers.js
  Starteryou/backend/handlers/CompanyProfileHandlers.js
  Starteryou/backend/handlers/JobApplicationHandlers.js
  Starteryou/backend/handlers/JobHandlers.js
  Starteryou/backend/handlers/ProfileHandlers.js
  Starteryou/backend/jest.config.js
  Starteryou/backend/jsconfig.json
  Starteryou/backend/package-lock.json
  Starteryou/backend/package.json
  Starteryou/backend/routes/bookmarkRoutes.js
  Starteryou/backend/routes/companyProfileRoutes.js
  Starteryou/backend/routes/jobApplicationRoutes.js
  Starteryou/backend/routes/jobRoutes.js
  Starteryou/backend/routes/profileRoutes.js
  Starteryou/frontend/src/components/JobFeedPage/CreateJobCard.jsx
Labels: Testing

#239 Added test cases for team and text route endpoints
  Starteryou/backend/__test__/TextRoutes.test.js
  Starteryou/backend/__test__/teamRoutes.test.js
  Starteryou/backend/handlers/TextHandlers.js
  Starteryou/backend/metadata/storeMetadataInDB.js
  Starteryou/backend/package-lock.json
  Starteryou/backend/routes/textRoutes.js
  Starteryou/frontend/public/STARTERYOU PRIVACY POLICY.pdf
  Starteryou/frontend/public/STARTERYOU TERMS OF SERVICE.pdf
  Starteryou/frontend/src/components/Landing/BestJob.jsx
  Starteryou/frontend/src/components/Landing/BestJob2.jsx
  Starteryou/frontend/src/pages/HomePage.jsx
Labels: Testing

#241 Replaced Console Logs with Winston Logger
  Starteryou/backend/cache/config/cacheConfig.js
  Starteryou/backend/cache/utils/cacheMiddleware.js
  Starteryou/backend/cache/utils/cacheMiddlewareJob.js
  Starteryou/backend/cache/utils/cacheQuery.js
  Starteryou/backend/cache/utils/cacheQueryJob.js
  Starteryou/backend/cache/utils/invalidateCache.js
  Starteryou/backend/db.js
  Starteryou/backend/handlers/BookmarkHandlers.js
  Starteryou/backend/handlers/CompanyProfileHandlers.js
  Starteryou/backend/handlers/JobApplicationHandlers.js
  Starteryou/backend/handlers/JobHandlers.js
  Starteryou/backend/handlers/ProfileHandlers.js
  Starteryou/backend/middleware/apiLogger.js
  Starteryou/backend/routes/authRoutes.js
  Starteryou/backend/routes/fileRoutes.js
  Starteryou/backend/routes/index.js
  Starteryou/backend/routes/sessionRoutes.js
  Starteryou/backend/routes/textRoutes.js
  Starteryou/backend/seedDatabase.js
  Starteryou/backend/server.js
  Starteryou/backend/utils/logger.js
  Starteryou/backend/utils/mongoTester.js
  Starteryou/backend/utils/testMongo.js
Labels: enhancement

#238 Testing for Caching
  Starteryou/backend/__test__/cacheMiddleware.test.js
  Starteryou/backend/__test__/cacheQuery.test.js
  Starteryou/backend/__test__/invalidateCache.test.js
  Starteryou/backend/jest.config.js
  Starteryou/backend/package-lock.json
  Starteryou/backend/package.json
Labels: Testing

#237 Cookie Mechanism Testing
  Starteryou/backend/jsconfig.json
  Starteryou/backend/package.json
  Starteryou/backend/test/sessionRoutes.test.js
  Starteryou/backend/test/sessionTimeout.test.js
  Starteryou/frontend/package-lock.json
  Starteryou/frontend/src/components/Common/SessionExpired.jsx
Labels: Testing

#246 PR Description: Update Cookie Security Settings for Cross-Origin Support
  Starteryou/backend/server.js
Labels: bug
