Repository starteryouInc/Starteryou-Website, pull requests merged in 2025-01, with the labels that each got.

#78 Authentication: Registration and Login Endpoints
  Starteryou/backend/models/UserModel.js
  Starteryou/backend/package.json
  Starteryou/backend/routes/authRoutes.js
  Starteryou/backend/routes/index.js
  Starteryou/backend/server.js
  Starteryou/frontend/package-lock.json
  Starteryou/frontend/src/App.jsx
  Starteryou/frontend/src/components/Auth/AdminSignup.jsx
  Starteryou/frontend/src/components/Auth/LoginPage.jsx
  package-lock.json
Labels: good first issue

#90 Implemented Text Editing API on HomePage.
  Starteryou/backend/package-lock.json
  Starteryou/frontend/src/components/Landing/Banner.jsx
  Starteryou/frontend/src/components/Landing/BestBuddy.jsx
  Starteryou/frontend/src/components/Landing/BestJob.jsx
  Starteryou/frontend/src/components/Landing/BestJob2.jsx
  Starteryou/frontend/src/components/Landing/BestJob3.jsx
  Starteryou/frontend/src/components/Landing/BestJob4.jsx
  Starteryou/frontend/src/components/Landing/Blog.jsx
  Starteryou/frontend/src/components/Landing/Hero.jsx
  Starteryou/frontend/src/index.css
Labels: enhancement

#115 Manage Team Section: Add and Delete Options
  Starteryou/backend/models/TeamMember.js
  Starteryou/backend/routes/teamRoutes.js
  Starteryou/backend/server.js
  Starteryou/frontend/docs/frontend/BetterFuture.jsx.html
  Starteryou/frontend/docs/frontend/HeroAbout.jsx.html
  Starteryou/frontend/docs/frontend/OurMission.jsx.html
  Starteryou/frontend/docs/frontend/OurVision.jsx.html
  Starteryou/frontend/docs/frontend/Team.jsx.html
  Starteryou/frontend/docs/frontend/TechTeam.jsx.html
  Starteryou/frontend/docs/frontend/global.html
  Starteryou/frontend/docs/frontend/index.html
  Starteryou/frontend/docs/frontend/module-OurVision.html
  Starteryou/frontend/public/AboutPage/Team/avatar.png
  Starteryou/frontend/src/components/About/Team.jsx
  Starteryou/frontend/src/config/api.js
Labels: documentation, enhancement

#129 Enhance Navbar, Footer, Favicon, and Team Sections
  Starteryou/backend/models/TeamMember.js
  Starteryou/backend/routes/teamRoutes.js
  Starteryou/backend/server.js
  Starteryou/frontend/index.html
  Starteryou/frontend/public/Logo.svg
  Starteryou/frontend/public/favlogo.png
  Starteryou/frontend/public/prelogo.png
  Starteryou/frontend/public/starteryou text white.png
  Starteryou/frontend/public/tiktok.svg
  Starteryou/frontend/public/utube.svg
  Starteryou/frontend/src/components/About/Team.jsx
  Starteryou/frontend/src/components/About/TechTeam.jsx
  Starteryou/frontend/src/components/Common/Footer.jsx
  Starteryou/frontend/src/components/Common/Navbar.jsx
  Starteryou/frontend/src/pages/AboutPage.jsx
Labels: documentation, enhancement
